# Generated by Django 4.0.4 on 2022-04-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('restaurant_uniq_id', models.IntegerField(unique=True)),
                ('borough', models.CharField(max_length=300)),
                ('cuisine', models.CharField(max_length=300)),
                ('building', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=500)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(max_length=2)),
                ('score', models.SmallIntegerField(default=1)),
                ('fk_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_api.restaurant')),
            ],
        ),
    ]
